from suncast.backtest import (
    HourRow,
    bulk_rows,
    clean_days,
    flat_k,
    is_bulk,
    mae_bias,
    score_fixed,
    score_lodo,
)
from suncast.models import PanelConfig
from suncast.pvmodel import Params, expected_w


def _row(day, h, cs, pv=100.0):
    return HourRow(ts=f"{day}T{h:02d}:00", day=day, gti=500.0, t_air=20.0, pv=pv, cs=cs)


PANEL = PanelConfig()


def _bulk_row(day, h, gti, t_air, pv):
    return HourRow(ts=f"{day}T{h:02d}:00", day=day, gti=gti, t_air=t_air, pv=pv, cs=3.0)


def test_is_bulk_range():
    assert is_bulk(3.0) and is_bulk(2.5)
    assert not is_bulk(2.4) and not is_bulk(3.5) and not is_bulk(4.0)


def test_bulk_rows_filters():
    rows = [_row("2026-06-01", 8, 3.0), _row("2026-06-01", 9, 4.0)]
    assert [r.ts for r in bulk_rows(rows)] == ["2026-06-01T08:00"]


def test_clean_days_threshold():
    # Day A: 4 daylight hours, 4 bulk -> clean. Day B: 4 daylight, 1 bulk -> not.
    a = [_row("A", h, 3.0) for h in range(4)]
    b = [_row("B", 0, 3.0)] + [_row("B", h, 4.0) for h in range(1, 4)]
    # Non-daylight (pv<=5) hours are ignored by the fraction.
    a.append(_row("A", 20, 5.0, pv=0.0))
    assert clean_days(a + b) == {"A"}


def test_mae_bias():
    # preds 110,90 vs actual 100,100 -> errors 10,10 mae=10; bias mean(10,-10)=0
    assert mae_bias([(110.0, 100.0), (90.0, 100.0)]) == (10.0, 0.0)
    assert mae_bias([]) == (0.0, 0.0)


def test_flat_k_is_median_daily_ratio():
    # Day1: base = 260*0.5 = 130; pv 65 -> ratio 0.5.
    # Day2: base = 130; pv 39 -> ratio 0.3. Median of {0.5,0.3} = 0.4.
    rows = [_bulk_row("D1", 8, 500.0, 20.0, 65.0), _bulk_row("D2", 8, 500.0, 20.0, 39.0)]
    assert abs(flat_k(rows, PANEL) - 0.4) < 1e-9


def test_score_fixed_zero_error_on_self_consistent_data():
    p = Params(k=0.5, gamma=-0.004)
    rows = [_bulk_row("D1", h, 300.0, 20.0, expected_w(300.0, 20.0, PANEL, p)) for h in range(3)]
    mae, bias = score_fixed(rows, PANEL, p)
    assert mae < 1e-9 and abs(bias) < 1e-9


def test_score_lodo_predicts_held_out_day():
    # Data generated by a true M2; LODO fit on other days should predict the
    # held-out day near-perfectly since all days share the same law.
    true = Params(k=0.5, gamma=-0.004)
    rows = []
    for day, t_air in (("D1", 5.0), ("D2", 20.0), ("D3", 35.0)):
        for gti in (200.0, 400.0, 600.0):
            expected = expected_w(gti, t_air, PANEL, true)
            rows.append(_bulk_row(day, int(gti // 100), gti, t_air, expected))
    mae, _bias = score_lodo(rows, PANEL)
    assert mae < 1e-6


def test_score_lodo_penalizes_when_days_disagree():
    # Two days with different efficiency (k). Correct LODO trains on the OTHER
    # day, so held-out predictions are genuinely wrong -> nonzero MAE. A leak
    # (training on the held-out day) would fit it exactly -> ~0 MAE. This pins
    # the r.day != held exclusion that noiseless data can't distinguish.
    from suncast.pvmodel import Params, expected_w

    rows = []
    for day, k in (("D1", 0.4), ("D2", 0.8)):
        p = Params(k=k, gamma=0.0)
        for gti in (200.0, 400.0, 600.0):
            rows.append(
                HourRow(
                    f"{day}T{int(gti // 100):02d}:00",
                    day,
                    gti,
                    20.0,
                    expected_w(gti, 20.0, PANEL, p),
                    3.0,
                )
            )
    mae, _bias = score_lodo(rows, PANEL)
    assert mae > 10.0


def test_archive_url_has_both_hourly_vars():
    from suncast.backtest import archive_url_temp

    u = archive_url_temp(48.83, 8.28, "2026-06-01")
    assert "archive-api.open-meteo.com" in u
    assert "global_tilted_irradiance" in u and "temperature_2m" in u
    assert "start_date=2026-06-01" in u and "end_date=2026-06-01" in u
    assert "timezone=UTC" in u


def test_parse_archive_maps_hour_to_gti_and_temp():
    from suncast.backtest import parse_archive

    body = (
        b'{"hourly": {"time": ["2026-06-01T11:00", "2026-06-01T12:00"],'
        b' "global_tilted_irradiance": [500.0, 800.0],'
        b' "temperature_2m": [18.0, 24.0]}}'
    )
    out = parse_archive(200, body)
    assert out["2026-06-01T11:00:00+00:00"] == (500.0, 18.0)
    assert out["2026-06-01T12:00:00+00:00"] == (800.0, 24.0)


def test_parse_archive_errors():
    import pytest

    from suncast.backtest import parse_archive

    with pytest.raises(ValueError):
        parse_archive(500, b"")
    with pytest.raises(ValueError):
        parse_archive(200, b"not json")
